### ISSUE TITLE
Module stopped working

### ISSUE THREAD

**Issue by vschinazi** [pixxelfriend/MMM-Luftdaten#2]
Sensor data no longer appears or refreshes. 
Can you help?

**Comment by pixxelfriend** [comment]
Hi, 

can you please provide me your current config and your current MM version? Does the date still updates?

**Comment by vschinazi** [comment]
Hi Thank you for the quick reply.
The issue is that the data does not update (see screenshot).

MM version: 2.13.0

Config:

{
	module: "MMM-Luftdaten",
	position: "bottom_center",
	config: {
	sensors: [47451,47452],
	fetchInterval: 5,
	timeOnly: true,
	}
	},


Thank you
![20211128_182508](https://user-images.githubusercontent.com/2072586/143735246-c7e53344-f0fe-42c7-a613-6dc08a1756ef.jpg)

**Comment by vschinazi** [comment]
Log data:

[2021-11-28 18:05:46.786] [ERROR]  MMM-Luftdaten: FetchError: request to https://data.sensor.community/airrohr/v1/sensor/47451/ failed, reason: certificate has expired
[2021-11-28 18:05:46.799] [ERROR]  MMM-Luftdaten: FetchError: request to https://data.sensor.community/airrohr/v1/sensor/47452/ failed, reason: certificate has expired

**Comment by pixxelfriend** [comment]
Thanks for providing the logs too! The Message says that the server certificate is not valid anymore, but it is valid until 31th december 2021.
Can you please check the local time at your pi? It seems that this is not correct. You should get it by running the command "time" in the shell. Otherwise your should try to restart the pi.

**Comment by vschinazi** [comment]
I ran time in the shell and got this:

pi@raspberrypi:~ $ time

real	0m0.000s
user	0m0.000s
sys	0m0.000s


and in my GUI it is showing me the correct time.  I have also restarted but it did not work. Any ideas?

**Comment by pixxelfriend** [comment]
Sorry, i meant the command date. Is the date still correct or just the time?

**Comment by vschinazi** [comment]
pi@raspberrypi:~/MagicMirror $ date
Sun 28 Nov 19:54:36 AEST 2021

The date and time are correct.

Is there a way to just force renew the certificate?

**Comment by pixxelfriend** [comment]
I found this [issue](https://github.com/node-fetch/node-fetch/issues/568. ) regarding the certificate warning and it seems to be solved in electron 13.5.1. , which is used by the latest MM Version. Seems that [letsencrypt has replaced their root certificate](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)

I downgraded the 13.5.0, an got exactly the same error. After installng electron 13.5.1 it worked again. 

What you can do now: 

1. try to update MM to the latest version or just update electron to 13.5.1 (depending on your other modules, you should be very carefully, because some may not support the latest MM version )

2. When you need very fast solution, go to MMM-Luftdaten/node_helper.js and change the url in line 8 from https to http.

3. If you have access to the sensors in your local network, then you could also try to setup them directly. Its much faster and you can reduce the intervall of fetching data.

**Comment by vschinazi** [comment]
Hi - First, let me thank you again for all the attention! I really appreciate it. I will try updating electron. I do not want to risk updating MM because everything else is working beautifully. If all fails, I will try the quick change in Line 8. 

Finally, the sensors are in my local network. the Pi is connected there but I have no idea how to set this up. Maybe i can annoy you another time for that :)

Thank you -- this has been very useful. I'll send you a note when I get it working.

**Comment by pixxelfriend** [comment]
You´re welcome. Nice to know, that there is anyone else who uses this :) 
 
If you know the ip adress of your sensor and if its not password protected, you could try to call this url in your browser: 
http://SENSOR_IP_ADRESS/data.json

If that works, you just need replace sensors by `sensorHost` and provide the ip adress. 

```
{
module: "MMM-Luftdaten",
position: "bottom_center",
config: {
//sensors: [47451,47452],
sensorHost: "SENSOR_IP_ADRESS" // e.g. 192.168.10.xx
fetchInterval: 5,
timeOnly: true,
}
},
```

**Comment by OmaBosselt** [comment]
Hi!

Ich habe den MM gerade installiert und es funktioniert bei mir ach nicht. Kann es sein, dass sich die API geaendet hat?
Luftaden infoist ja umgezogen.

**Comment by pixxelfriend** [comment]
Hi, 

die v1 Api scheint noch verfügbar und aktuell zu sein. [Opendata Stuttgart Wiki](https://github.com/opendata-stuttgart/meta/wiki/APIs)
Versuche mal die folgende URL mit deiner Sensor ID aufzurufen und ob du da Daten deines Sensors siehst (66680 durch deine ID ersetzen): 
`https://data.sensor.community/airrohr/v1/sensor/66680/`

Wenn der Sensor bei dir im lokalen Netzwerk hängt, kannst du auch die Daten direkt abgreifen, indem du `sensorHost` setzt. Falls nichts davon hilft, dann erstelle bitte nochmal ein neues Issue.

**Comment by OmaBosselt** [comment]
Hi!
Funktioniert. Ich glaube es lag an meinem WLAN am Rasp. Das klemmt etwas und ich war zu ungeduldig. Omas haben halt nicht mehr so viel Zeit. ; o)
Der Link oben funktioniert auch. Danke fuer dieses nette tool.
